[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "looper"
version="0.0.1"
description = "Static analysis tool for determining tight upper bounds on execution cost"
keywords = ["static analysis", "COST", "Looper", "execution cost"]
readme = "README.md"
license = {file = "LICENSE"}
authors = [
    {name = "Jan Pánek", email = "panekjan.j@seznam.cz" }
]
maintainers = [
    {name = "Jan Pánek", email = "panekjan.j@seznam.cz" }
]
# requirements
requires-python = ">=3.10"
dependencies = [
    "z3-solver",
    "click",
    "pyyaml",
    "pytest",
    "pytest-cov"
]

[tool.setuptools]
include-package-data = true 

[tool.setuptools.packages.find]
where = ["looper", "looper/cpp_modules"]

[tool.setuptools.package-data]
"cpp_modules.expression" = ["expression/*.so"]
"cpp_modules.labeled_transition_system" = ["labeled_transition_system/*.so"]
"cpp_modules.difference_constraint_program" = ["difference_constraint_program/*.so"]
"cpp_modules.reset_chain_graph" = ["reset_chain_graph/*.so"]
"cpp_modules.variable_flow_graph" = ["variable_flow_graph/*.so"]
"cpp_modules.lts_constructor" = ["lts_constructor/*.so"]

[project.scripts]
looper = "looper:cli_run_analysis"